# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  JOB_LIST_API_URL: https://api.json-generator.com/templates/ZM1r0eic3XEy/data
  JOB_LIST_API_TOKEN: wm3gg940gy0xek1ld98uaizhz83c6rh2sir9f9fu
  NEXT_PUBLIC_MAP_API_KEY: AIzaSyDG7wZay36ZhRN8OQOxXzRwAC2HD10hWTY
  NEXT_PUBLIC_MAP_API_ID: 98247b3584c2f5c6
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run export
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: main
        folder: out # The folder the action should deploy.
